const {
  INVOICE_STATUS_VALUES,
  INVOICE_STATUSES,
} = require("../utils/invoiceUtils");

const mongoose = require("mongoose");

const InvoiceSchema = new mongoose.Schema(
  {
    orderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
      required: true,
      unique: true,
      index: true,
    },

    /*
     * Copied from the order when the invoice is created.
     * These fields make authorization and listing efficient.
     */
    orderedByUserId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    supplierId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    invoiceNumber: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      uppercase: true,
    },

    /*
     * Snapshot of order.calculatedTotal.
     * Never accept this field from the client.
     */
    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    status: {
      type: String,
      enum: INVOICE_STATUS_VALUES,
      default: INVOICE_STATUSES.DRAFT,
      required: true,
      index: true,
    },

    /*
     * Generated by Multer or another storage provider.
     * This value should not be accepted from req.body.
     */
    storagePath: {
      type: String,
      default: null,
    },

    originalFileName: {
      type: String,
      default: null,
    },

    mimeType: {
      type: String,
      default: null,
    },

    fileSize: {
      type: Number,
      min: 0,
      default: null,
    },

    submittedAt: {
      type: Date,
      default: null,
    },

    approvedAt: {
      type: Date,
      default: null,
    },

    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);

InvoiceSchema.index({
  orderedByUserId: 1,
  status: 1,
  createdAt: -1,
});

InvoiceSchema.index({
  supplierId: 1,
  status: 1,
  createdAt: -1,
});

module.exports = mongoose.model("Invoice", InvoiceSchema);
